### ISSUE TITLE
Can no longer start a build by sending a post request

### ISSUE THREAD

**Issue by LBRapid** [defunkt/cijoe#65]
Previously, i was able to run something like `curl -d "run tests" http://localhost:4567" to start a build, but this is no blowing up with the following output. Any ideas?

```
== Sinatra/1.2.6 has taken the stage on 4567 for development with backup from WEBrick
[2011-08-04 12:23:35] INFO  WEBrick 1.3.1
[2011-08-04 12:23:35] INFO  ruby 1.8.7 (2011-02-18) [i686-darwin10.6.0]
[2011-08-04 12:23:35] INFO  WEBrick::HTTPServer#start: pid=70651 port=4567
Loaded Campfire notifier for source/spree.
TypeError - can't convert nil into String:
.rvm/gems/ruby-1.8.7-p334@spree/gems/json-1.5.3/lib/json/common.rb:148:in `initialize'
.rvm/gems/ruby-1.8.7-p334@spree/gems/json-1.5.3/lib/json/common.rb:148:in `new'
.rvm/gems/ruby-1.8.7-p334@spree/gems/json-1.5.3/lib/json/common.rb:148:in `parse'
```

**Comment by thiagodiniz** [comment]
I am having the same problem using the same curl statement, but in my case i use ruby 1.9.2

```
TypeError - can't convert nil into String:
 .rvm/gems/ruby-1.9.2-p290/gems/json-1.5.3/lib/json/common.rb:148:in `initialize'
 .rvm/gems/ruby-1.9.2-p290/gems/json-1.5.3/lib/json/common.rb:148:in `new'
 .rvm/gems/ruby-1.9.2-p290/gems/json-1.5.3/lib/json/common.rb:148:in `parse'
 .rvm/gems/ruby-1.9.2-p290/gems/cijoe-0.9.2/lib/cijoe/server.rb:32:in `block in <class:Server>'
```

**Comment by thiagodiniz** [comment]
I have find the solution. the curl data field should have the value "rebuild=true".

So the complete curl statement should be:

```
curl -d "rebuild=true" http://user:secrete@localhost:4567/
```

**Comment by zacharydanger** [comment]
Patch to make this not fail hard #77.
