### ISSUE TITLE
Stack level too deep

### ISSUE THREAD

**Issue by ethnt** [defunkt/cijoe#75]
When I run CIJoe with Sinatra 1.2.7, I'm getting this:

```
:public is no longer used to avoid overloading Module#public, use :public_folder instead
    from /home/ethan/.rvm/gems/ruby-1.9.2-p290@fhsclock/gems/cijoe-0.9.2/lib/cijoe/server.rb:12:in `<class:Server>'
/home/ethan/.rvm/gems/ruby-1.9.2-p290@fhsclock/bin/cijoe:19: stack level too deep (SystemStackError)
```

The first error is easily fixable, but I'm not sure what the deal is with the SystemStackError.

**Comment by germs12** [comment]
I got the same thing this morning on my first run.  I'm happy to help debug, but this is my first time using CIJoe.

<code>:public is no longer used to avoid overloading Module#public, use :public_folder instead
    from /Users/jamesthullbery/.rvm/gems/ruby-1.9.2-p180@cijoe/gems/cijoe-0.9.2/lib/cijoe/server.rb:12:in `class:Server'
/Users/jamesthullbery/.rvm/gems/ruby-1.9.2-p180@cijoe/bin/cijoe:19: stack level too deep (SystemStackError)</code>

**Comment by mptre** [comment]
Probably due to this [bug](https://github.com/defunkt/cijoe/pull/72).

**Comment by ethnt** [comment]
Looks like it. ETA on merge into master?

**Comment by mptre** [comment]
Sorry. Can't tell since I'm not the owner.

**Comment by ExtractMethod** [comment]
I got the same problem. Installing sinatra 1.2.0 seems to have resolved this for me. Maybe the gemspec can be updated to specify the sinatra version.

**Comment by mptre** [comment]
Ok, thanks for the info.

**Comment by oren** [comment]
sinatra 1.2 didn't work for me. 1.2.7 seems to be fine.

**Comment by jurgens** [comment]
Got same problem with sinatra 1.3.1

~/rails/jw_walls$ cijoe .

:public is no longer used to avoid overloading Module#public, use :public_folder instead
    from /home/jurgen/.rvm/gems/ruby-1.9.3-p0@rails3/gems/cijoe-0.9.2/lib/cijoe/server.rb:12:in `class:Server'
/home/jurgen/.rvm/gems/ruby-1.9.3-p0@rails3/bin/cijoe:19: stack level too deep (SystemStackError)

gem list sinatra
**\* LOCAL GEMS ***
sinatra (1.3.1)

**Comment by n8mlr** [comment]
Looks like this happens when Sinatra has problems binding with port 4567. I ran into the same issue on a machine that had a firewall blocking this port.

**Comment by jurgens** [comment]
There should not be any binding problems with my setup. Works fine with Sinatra 1.2.7
